spring.application.name=gateway-service
server.servlet.context-path=/gw
spring.cloud.gateway.routes[0].id=tenant_service_node1_route
spring.cloud.gateway.routes[0].uri=lb://tenant-service-node1
spring.cloud.gateway.routes[0].predicates[0]=Path=/tenant/**
spring.cloud.gateway.routes[0].predicates[1]=Header=X-API-VERSION, tenant1

spring.cloud.gateway.routes[1].id=tenant_service_node2_route
spring.cloud.gateway.routes[1].uri=lb://tenant-service-node2
spring.cloud.gateway.routes[1].predicates[0]=Path=/tenant/**
spring.cloud.gateway.routes[1].predicates[1]=Header=X-API-VERSION, tenant2

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/